version: '3'
services:
  backend:
    hostname: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
    - "3000:3000"
    env_file:
    - backend/.env
  frontend:
    hostname: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
    - "8080:3000"

networks:
  idp-network:
